application: kitetrickprogression
version: test
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "30d"

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  mime_type: image/x-icon

- url: /apple-touch-icon.png
  static_files: static/img/apple-touch-icon.png
  upload: static/img/apple-touch-icon.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /googled797ca5faef5af4c.html
  static_files: static/googled797ca5faef5af4c.html
  upload: static/googled797ca5faef5af4c.html

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: main.app

# vim: set ts=2 sw=2:
